# Site settings
title: Lee Sung Jun PortFolio
description: portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://sujl950620.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Developer 이성준
user_description:  
user_title: Web Developer
email: sujl95@naver.com
github_username:  sujl950620
gplus_username:  ""
# Google-analytics
google-analytics:
  id: ""
exclude: ['package.json', 'src' , 'node_modules']
host: 0.0.0.0
port: 4000
