# Site settings
title: 신입 개발자 이성준 포트폴리오 입니다
description: portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url : "https://sujl950620.github.io"
baseurl : ""
# User settings
username: Developer 이성준
user_description: 안녕하십니까 신입 개발자 이성준입니다. 
user_title: Web Developer
email: sujl95@naver.com
github_username:  sujl950620
gplus_username:  ""
remote_theme : 
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
